### PR TITLE
Fix advancedcpp2 library not found

### PR DESCRIPTION
**Pull request by sudo-panda**
This fixes the `test03a_namespace_lookup_on_update` test.

### CODE REVIEW

**Comment by vgvassilev** [comment]
This probably will need @wlav’s help if that change seems acceptable.

**Comment by sudo-panda** [comment]
We are currently using this everywhere else. Case in point: https://github.com/compiler-research/cppyy/blob/888b1e8f36ca3a5d71ce06319bebf6fb725ca3d9/test/test_advancedcpp.py#L6-L7

IMO we can add the functionality of not using `.h` and revert this change later.

**Comment by wlav** [comment]
Not following this one ... currently, it already is.
```
        lib2 = cppyy.load_reflection_info("advancedcpp2Dict")
```

so the `lib2 = cppyy.load_library("advancedcpp2")` was a change you made locally?

But then also:
a) for sure you can NOT have `.so` as on Windows it will be `.dll` and on Mac for a while it was `.dylib` ...
b) the header is implicitly loaded by the dictionary, which is the point of the test

**Comment by vgvassilev** [comment]
We probably need to have a discussion about what to do with this autoloading feature. We might need to solve it using c++ modules. Is there some representative test case we could look at?

**Comment by wlav** [comment]
Just loading a basic class should be the bulk of it (I don't think templates or functions were ever supported): https://cppyy.readthedocs.io/en/latest/utilities.html#example

**Pull request closed without merging**
