### PR TITLE
cppdef is not expected to print on stderr.

### PR DESCRIPTION
**Pull request by vgvassilev**

### CODE REVIEW

**Comment by vgvassilev** [comment]
@wlav, this change was supposed to fix an error in `test_regression.py::TestREGRESSION::test04_avx` which showed:

<summary>

```
test_regression.py int check_avx() { return (int) __AVX__; }
input_line_12:1:32: error: use of undeclared identifier '__AVX__'
int check_avx() { return (int) __AVX__; }
                               ^
```

</summary>
<details>

```

python -m pytest --runxfail --capture=no test_regression.py::TestREGRESSION::test04_avx 
============================================================= test session starts =============================================================
platform linux -- Python 3.6.9, pytest-7.0.1, pluggy-1.0.0
rootdir: /home/vvassilev/workspace/builds/scratch/cppyy/cppyy
plugins: xdist-3.0.2
collected 1 item                                                                                                                              

test_regression.py int check_avx() { return (int) __AVX__; }
input_line_12:1:32: error: use of undeclared identifier '__AVX__'
int check_avx() { return (int) __AVX__; }
                               ^
F

================================================================== FAILURES ===================================================================
__________________________________________________________ TestREGRESSION.test04_avx __________________________________________________________

self = <test.test_regression.TestREGRESSION object at 0x7ffff4507860>

    @mark.xfail
    def test04_avx(self):
        """Test usability of AVX by default."""
    
        import cppyy, subprocess
    
        has_avx = False
        try:
            f = open('/proc/cpuinfo', 'r')
            for line in f.readlines():
                if 'avx' in line:
                    has_avx = True
                    break
            f.close()
        except Exception:
            try:
                cli_arg = subprocess.check_output(['sysctl', 'machdep.cpu.features'])
                has_avx = 'avx' in cli_arg.decode("utf-8").strip().lower()
            except Exception:
                pass
    
        if has_avx:
>           assert cppyy.cppdef('int check_avx() { return (int) __AVX__; }')

test_regression.py:126: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

src = 'int check_avx() { return (int) __AVX__; }'

    def cppdef(src):
        """Declare C++ source <src> to Cling."""
        with _stderr_capture() as err:
            print(src)
            errcode = gbl.InterOp.Declare(gbl.cling.runtime.gCling, src)
        if not errcode == 0 or err.err:
            if 'warning' in err.err.lower() and not 'error' in err.err.lower():
                warnings.warn(err.err, SyntaxWarning)
                return True
>           raise SyntaxError('Failed to parse the given C++ code%s' % err.err)
E             File "<string>", line None
E           SyntaxError: Failed to parse the given C++ code

../../.venv_no_debug/lib/python3.6/site-packages/cppyy/__init__.py:206: SyntaxError
============================================================== warnings summary ===============================================================
test/test_regression.py::TestREGRESSION::test04_avx
  /home/vvassilev/workspace/builds/scratch/cppyy/cppyy-backend/python/cppyy_backend/loader.py:139: UserWarning: No precompiled header available (/home/vvassilev/workspace/builds/scratch/cppyy/cppyy-backend/python/cppyy_backend/etc not writable, set CLING_STANDARD_PCH); this may impact performance.
    warnings.warn('No precompiled header available (%s); this may impact performance.' % msg)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================================================== short test summary info ===========================================================
FAILED test_regression.py::TestREGRESSION::test04_avx -   File "<string>", line None
======================================================== 1 failed, 1 warning in 9.92s =========================================================

```
</details>

However both clang and gcc do not seem to define these macros by default:

```gcc -dM -E - < /dev/null | egrep "SSE|AVX" | sort
#define __SSE__ 1
#define __SSE2__ 1
#define __SSE2_MATH__ 1
#define __SSE_MATH__ 1
```

So the question is how was this test supposed to work?

**Comment by wlav** [comment]
The test exists precisely b/c AVX is not enabled by default: cppyy sends `-march=native` to cling (this is important to the math folks), which enables AVX if the platform supports it (the test already checks for that). If the test fails, that means that `-march=native` isn't properly propagated. This code is in the backend, which passes it through `EXTRA_CLING_ARGS`.

**Comment by vgvassilev** [comment]
Ah, I got it now. Ok that's compiler-research/cppyy-backend#49

**Comment by vgvassilev** [comment]
> Not a fan of hard-wiring this in C++ code (same for `-std=c++17`). It's fine to have the setting in C++ rather than Python, but it has to be configurable.
> 
> For example, the memory layout of classes in Eigen changes when AVX is enabled. Thus, if you have a compiled 3rd party library based on Eigen, you have to be able to match compiler flags or crashes ensue.

Do you have a particular interface in mind? I am happy to not hardcode this.

**Comment by wlav** [comment]
envars, like is current, should be fine.

To upgrade, perhaps, I've been wanting to split `EXTRA_CLING_ARGS` into two pieces: user provided and default. (I also don't like the naming choice of `EXTRA_CLING_ARGS` over `CLING_EXTRA_ARGS` btw.). In that case there could be a user-provided `EXTRA_CLING_ARGS`/`CLING_EXTRA_ARGS` and an envar that enables/disables default additions, e.g. `CLING_USE_DEFAULT_ARGS`. By default on, but if set to `0`, then nothing is added.

The `-std=c++17` (or whatever is appropriate) is taken from the build args currently, same as `cling-config`, and currently `-O2` is added as well.

And important other use of this variable has been `-g` (although that didn't always work), which is now superseded by `CLING_DEBUG`.

**Comment by vgvassilev** [comment]
Do you think we can create the interpreter on the python side and pass it back to CPyCppyy? This way we can we as flexible as we like?

**Comment by wlav** [comment]
Sounds clunky ... for the bootstrap, you then can NOT use cppyy to provide the bindings (which requires the interpreter), then it bootstraps, then it "resets" the interpreter known to cppyy from whatever manual bindings were used first to the true ones.

Note also that there's no way on the Python side to pass arguments to cppyy other than envars, so it'd basically be doubly complicated for no benefit.

**Comment by vgvassilev** [comment]
Ok, I think I captured the discussion partially in compiler-research/cppyy-backend#51

**Pull request merged**
