### PR TITLE
Remove the reference to N

### PR DESCRIPTION
**Pull request by sudo-panda**
The operator tests reference `N` in their setup but it is not used anywhere. It is also the current source of failure for these tests.

### CODE REVIEW

**Comment by vgvassilev** [comment]
I would generally ask @wlav for such changes. Can you cc him when we change test cases?

**Comment by vgvassilev** [comment]
@wlav, so this change looks good to you?

**Comment by wlav** [comment]
No, I don't like to leave commented code around for future maintainers to puzzle over. Just remove the line completely.

**Comment by vgvassilev** [comment]
@sudo-panda, can you move that change upstream and backport the commit?

**Comment by sudo-panda** [comment]
> @sudo-panda, can you move that change upstream and backport the commit?

Just to be sure, you mean wlav/cppyy.

**Comment by vgvassilev** [comment]
> > @sudo-panda, can you move that change upstream and backport the commit?
> 
> Just to be sure, you mean wlav/cppyy.

Yes.

**Pull request closed without merging**
