### PR TITLE
[test] Update tags

### PR DESCRIPTION
**Pull request by Vipul-Cariappa**

### CODE REVIEW

**Comment by Vipul-Cariappa** [comment]
Hi @vgvassilev could you please merge this PR after the tests pass. I suspect some may fail with OSX-cling. I will update the PR if they fail. As I don't have access to a device with OSX I need to rely on GitHub workflows to update the test tags.

Please rerun the workflow at https://github.com/compiler-research/cppyy-backend/pull/110 after merging this PR.

ping @aaronj0

**Comment by Vipul-Cariappa** [comment]
I cannot figure out the proper tags from the logs. @aaronj0 could you please have a look.

**Comment by vgvassilev** [comment]
Can you rebase this PR?

**Comment by Vipul-Cariappa** [comment]
Looks like the change I made has been included in main. 👍🏽

**Pull request closed without merging**
