### PR TITLE
removing xfail on anonymous struct and union tests

### PR DESCRIPTION
**Pull request by Vipul-Cariappa**
fixed by compiler-research/CppInterOp#321

### CODE REVIEW

**Comment by Vipul-Cariappa** [comment]
ping @vgvassilev

**Comment by Vipul-Cariappa** [comment]
The [Ubuntu cling](https://github.com/compiler-research/cppyy/actions/runs/10898087213/job/30256670946?pr=99) failure does not look like my doing.

**Comment by aaronj0** [comment]
Please rebase into a single commit

**Comment by Vipul-Cariappa** [comment]
@aaronj0, I have rebased into a single commit. 👍🏽

**Review by aaronj0 — APPROVED** [review]

**Pull request merged**
